version: '3.1'
services:
  cache:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  app:
    container_name: app-reserfasi-tiket
    image: app-reserfasi-tiket
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - dbPostgre
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbPostgre:5432/reserfasi_tiket
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_MVC_PATHMATCH_MATCHING-STRATEGY=ANT_PATH_MATCHER
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=TRUE
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER=TRACE
      - LOGGING_EVEL_ORG_SPRINGFRAMEWORK=DEBUG
  dbPostgre:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=postgres
        - POSTGRES_DB=reserfasi_tiket